# Generated by Django 4.2.1 on 2023-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
