# Generated by Django 4.2.1 on 2023-06-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
