# Generated by Django 4.2.4 on 2023-10-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_alter_despesa_descricao'),
        ('core', '0002_alter_gasto_tipo_alter_gasto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.despesa'),
        ),
    ]
