# Generated by Django 4.2.4 on 2023-10-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gasto_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='user_id',
            new_name='user',
        ),
    ]
