# Generated by Django 4.2.4 on 2023-10-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_id_gasto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='user',
            new_name='usuario',
        ),
    ]
