# Generated by Django 4.2.4 on 2023-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('VE', 'Vendedor'), ('CE', 'Corretor'), ('AD', 'Administrador')], default='VE', max_length=2),
        ),
    ]
