# Generated by Django 4.2.4 on 2023-10-27 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_rename_user_gasto_usuario'),
        ('correcoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcao',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correcao',
            name='gasto',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='core.gasto'),
        ),
        migrations.AlterField(
            model_name='correcao',
            name='usuario',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
